spring:
  profiles:
    active:
#      - test

  datasource:
#    url: jdbc:h2:~/openapi-board
    driver-class-name: ${db_classname}
    url: jdbc:${db_url}
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: ${hibernate_dialect}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.glassfish.jersey.logging: INFO


# Specific App configs:
