users:
  entries:
    -
      name: admin
      password: test
      roles: ['READER', 'AGENT', 'MANAGER']

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  h2:
    console:
      enabled: true
#  servlet:
#    context-path: /api