users:
  entries:
    -
      name: admin
      password: test
      roles: ['READER', 'AGENT', 'MANAGER']

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 572
    username: ricardo.test
    password: blaFromSecrets
    properties:
      - name: mail.smtp.auth
        value: true


server:
  h2:
    console:
      enabled: true
#  servlet:
#    context-path: /api

env:
  server-address: http://localhost:8080/