users:
  entries:
    -
      name: admin
      password: test
      roles: ['READER', 'AGENT', 'MANAGER']

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  mail:
    host: localhost
    port: 1025
    username: oab_server
    password: superSecret
    protcol: smtp
    properties:
#      - name: mail.smtp.auth
#        value: true
      - name: mail.smtp.starttls
        value: true

server:
  h2:
    console:
      enabled: true
#  servlet:
#    context-path: /api

env:
  server-address: http://localhost:8080
  mail-notification-enabled: true
  main-namespace: Production

jwt:
  private:
    key: DXnC^E8xFm6-ectU4rXv8T7jNnxW2rdXazwxQvWwshCiEzcLQvMbDYAKECFBtyWWzqQnv5tzpGoWRdbNxXPmaLKR/jSx_FSWoij88uHaLu6zVQPfvPRUwAmRimqcUTba

#security:
#  ignored: /**