spring:
  datasource:
    #    url: jdbc:h2:~/openapi-board
    driver-class-name: org.h2.Driver
    url: h2:mem:openapi-board
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create