apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-app
  name: apenapi-board
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 80
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-app
  name: apenapi-board

spec:
  progressDeadlineSeconds: 600
  replicas: 1

  selector:
    matchLabels:
      app: front-app

  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - image: openapi-board-front:oab
        imagePullPolicy: Never
        name: openapi-board-front

        ports: 
          - name: http
            containerPort: 80

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
