apiVersion: v1
kind: Service
metadata:
  labels:
    app: openapi-board-backend
  name: openapi-board-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openapi-board-backend
  name: openapi-board-backend

spec:
  progressDeadlineSeconds: 600
  replicas: 1

  selector:
    matchLabels:
      app: openapi-board-backend

  template:
    metadata:
      labels:
        app: openapi-board-backend

    spec:
      containers:
      - image: oaboard-server:latest
        imagePullPolicy: Never
        name: openapi-board-backend

        ports: 
          - name: http
            containerPort: 8080

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
