apiVersion: v1
kind: Service
metadata:
  labels:
    app: swagger-ui
  name: swagger-ui
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090

  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swagger-ui
  name: swagger-ui

spec:
  progressDeadlineSeconds: 600
  replicas: 1

  selector:
    matchLabels:
      app: swagger-ui

  template:
    metadata:
      labels:
        app: swagger-ui

    spec:
      containers:
      - image: swagger-ui:oab
        imagePullPolicy: Never
        name: swagger-ui

        ports: 
          - name: http
            containerPort: 8090

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
