
# Fixed users for testing
users:
  entries:
    - name: admin
      password: test00
      roles: ['READER', 'MANAGER', 'BLUE_PERM', 'GREEN_PERM']
    - name: agent
      password: test00
      roles: ['READER', 'AGENT']
    - name: blue
      password: accessBlueOnly
      roles: ['READER', 'AGENT', 'BLUE_PERM']
    - name: green
      password: accessGreenOnly
      roles: ['READER', 'AGENT', 'GREEN_PERM']

#

spring:
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: false

    hibernate:
      ddl-auto: update

  mail:
    host: localhost
    port: 1025
    username: oab_server
    password: superSecret
    protocol: smtp
    properties:
#      - name: mail.smtp.auth
#        value: true
      - name: mail.smtp.starttls
        value: true

  h2:
    console.enabled: true


# App config -  Must be provided externally:

env:
  server-address: http://localhost:8080
  hooks-notification-enabled: true
  main-namespace: Production
  namespace:
    auto-create: true

jwt:
  private:
    key: DXnC^E8xFm6-ectU4rXv8T7jNnxW2rdXazwxQvWwshCiEzcLQvMbDYAKECFBtyWWzqQnv5tzpGoWRdbNxXPmaLKR/jSx_FSWoij88uHaLu6zVQPfvPRUwAmRimqcUTba


#security:
#  ignored: /**